import { Inter,Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "../components/nav/navbar"
import Footer from "../components/footer/footer"
// import { ThemeProvider } from "../components/context/ThemeContext";


const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"],
  weight:["900"]
 });


export const metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
     
      <div className="container">
      {/* <ThemeProvider> */}
       <Navbar/>
       {/* </ThemeProvider> */}
        {children}
        
        
        <Footer/>
      
        </div>
      
      

       
      </body>
    </html>
  );
}
